name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'

permissions:
  contents: read

defaults:
  run:
    working-directory: terraform

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_VAR_github_token: ${{ secrets.REPO_ADMIN }}
    steps:
      - uses: actions/checkout@v7

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: '1.16.1'

      - run: terraform init

      - run: terraform apply -auto-approve
